[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://arandua1-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/historias"
  to = "https://arandua1-production.up.railway.app/historias"
  status = 200
  force = true

[[redirects]]
  from = "/historias/*"
  to = "https://arandua1-production.up.railway.app/historias/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200